### ISSUE TITLE
View is vibrating

### ISSUE THREAD

**Issue by IncPlusPlus** [Franc1sco/aimbot#10]
When I enable aimbot, my view starts rocking side to side very rapidly. This occurs at all times until I shut aimbot off again. I recorded and attached a demo of this.

[rocking.zip](https://github.com/Franc1sco/aimbot/files/409954/rocking.zip)

**Comment by IncPlusPlus** [comment]
Solved. The normal recoil option was being buggy. I just use `sm_aimbot_norecoil 2`
Answered [here](https://forums.alliedmods.net/showpost.php?p=2445664&postcount=67).

**Comment by AdsL1221** [comment]
how run?
